Update __init__.py: cv.ipv4 -> cv.ipv4address()
Issue: AttributeError: module 'esphome.config_validation' has no attribute 'ipv4'

If we look at esphome config_validation.py file it has:
def ipv4address(value):

So I believe that should be used instead of ipv4

Docs: https://github.com/esphome/esphome/blob/dev/esphome/config_validation.py